- name: Create Datacenter
  hosts: 192.168.15.9
  tasks:
  - name: Create DataCenter
    community.vmware.vmware_datacenter:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      state: present
    delegate_to: 192.168.15.9
